### ISSUE TITLE
Model loader always defaults to CUDA regardless of what backend is being used.  Breaks systems without NVidia cards.  

### ISSUE THREAD

**Issue by NeedsMoar** [Ttl/ComfyUi_NNLatentUpscale#2]
I'm currently running the directml backend on Windows and got it working by removing explicit CUDA usage anywhere it was, and explicitly using CPU for the neural network;  torch didn't want to load the model on a directml device (which shows up as "privateuse0" type) for some reason.  I probably messed something up there;  normally both will just work until somebody comes along with a vendor specific extension   Might want to look into that.   Doesn't seem to be an issue converting it to the device type though since I was able to do that at the return from the upscale function without issues (see below), it was just the call to torch_load in resizer.   In my case it complained that privateuse0 wasn't in the list of types available.  "privateuse" with no zero was.  

Aside from that it works better than any of the other upscale methods which tended to be more dependent on the level of noise reduction in the final step from my limited testing so far.  

I should note that the first time I tried doing this I also had converted the return of the function in your checkin to use CPU as you did.  I was sending it to a second KSampler node (theoretically for detail but also to correct shape issues

**Comment by Ttl** [comment]
I'm not sure what the exact issue is. I changed the `torch.load` to the same method that ComfyUI uses so if that works with DirectML it should work here too.

**Comment by NeedsMoar** [comment]
Ooops left that at the same time.  I'm guessing that will work for me (and it'll keep ipex optimizers from being bypassed on Intel for people with those cards).  Check that last part about samplers running on CPU if the results are output to that device though, that's another bit of weirdness.

**Comment by NeedsMoar** [comment]
Just checking in to let you know that all is working as expected. Now it's off to complain to microsoft that torch.load can't load a model on a directml device identified by its own returned value when torch-directml is installed.  I think part of the issue is that they import the DirectML.dll library into python and call a bunch of native_ functions within it but when I popped open the library none of them are exported, nor are they documented anywhere

Works good for me so far.  :D
