### ISSUE TITLE
the result is bad

### ISSUE THREAD

**Issue by wen020** [Ttl/ComfyUi_NNLatentUpscale#3]
I test [ComfyUi_NNLatentUpscale](https://github.com/Ttl/ComfyUi_NNLatentUpscale) ,but i find the result is bad. And whats wrong?
I cost 13s from 512x512 upscale to 2048x2048
!python evaluation.py --test_path ./test --vae_path ./sd_xl_base_1.0_0.9vae.safetensors --resizer_path sdxl_resizer.pt --scale 4 --resolution 512

source img
![kim ji-won-01](https://github.com/Ttl/ComfyUi_NNLatentUpscale/assets/54690997/9c42fbf3-1075-463c-8d5d-fcfd0634faa3)

upscale img
![output_image (8)](https://github.com/Ttl/ComfyUi_NNLatentUpscale/assets/54690997/a561b6bd-b45c-47b7-b8c3-e02926413cbf)

**Comment by Ttl** [comment]
Only 1.0 to 2.0 upscale range is supported by the neural net. Also, the correct way to use it is as ComfyUI node. "evaluation.py" script is only for development.

**Comment by wen020** [comment]
Will the neural net optimize image content? Such as face restoration...

**Comment by ttulttul** [comment]
> Will the neural net optimize image content? Such as face restoration...

No, it won't do anything to optimize the face. This node only tries to upscale latents with a quality that is close to that of a full VAE Decode -> Upscale Image -> VAE Encode, which takes 20x longer...
