### ISSUE TITLE
what is wrong with the comfyui?

### ISSUE THREAD

**Issue by wen020** [Ttl/ComfyUi_NNLatentUpscale#4]
I run [NNLatentUpscale](https://github.com/Ttl/ComfyUi_NNLatentUpscale) with comfyui, but the result is bad. what is wrong with the comfyui?
![Snipaste_2023-12-08_16-17-21 (1)](https://github.com/Ttl/ComfyUi_NNLatentUpscale/assets/54690997/8631a228-2dda-4698-af4a-b32b012c5db4)

[test_nn_latent_upscale.json](https://github.com/Ttl/ComfyUi_NNLatentUpscale/files/13611338/test_nn_latent_upscale.json)

**Comment by Ttl** [comment]
It looks like you have issues with ComfyUI since the image from regular latent upscale doesn't work. You should ask about it on ComfyUI repository or other discussion forum.
